// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: tac.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_tac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type PingResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ServerName             string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion          string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	CertificateFingerprint string                 `protobuf:"bytes,3,opt,name=certificate_fingerprint,json=certificateFingerprint,proto3" json:"certificate_fingerprint,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_tac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingResponse) GetCertificateFingerprint() string {
	if x != nil {
		return x.CertificateFingerprint
	}
	return ""
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_tac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{2}
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	RoleCount     int32                  `protobuf:"varint,3,opt,name=role_count,json=roleCount,proto3" json:"role_count,omitempty"`
	ToolCount     int32                  `protobuf:"varint,4,opt,name=tool_count,json=toolCount,proto3" json:"tool_count,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,5,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_tac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfoResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *ServerInfoResponse) GetRoleCount() int32 {
	if x != nil {
		return x.RoleCount
	}
	return 0
}

func (x *ServerInfoResponse) GetToolCount() int32 {
	if x != nil {
		return x.ToolCount
	}
	return 0
}

func (x *ServerInfoResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_tac_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{4}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_tac_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{5}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_tac_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Components    []string               `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	Tools         []string               `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ApiType       string                 `protobuf:"bytes,6,opt,name=api_type,json=apiType,proto3" json:"api_type,omitempty"`
	MessageMode   string                 `protobuf:"bytes,7,opt,name=message_mode,json=messageMode,proto3" json:"message_mode,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Model         string                 `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_tac_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{7}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Role) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *Role) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Role) GetApiType() string {
	if x != nil {
		return x.ApiType
	}
	return ""
}

func (x *Role) GetMessageMode() string {
	if x != nil {
		return x.MessageMode
	}
	return ""
}

func (x *Role) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Role) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Role) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetRoleToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleToolsRequest) Reset() {
	*x = GetRoleToolsRequest{}
	mi := &file_tac_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleToolsRequest) ProtoMessage() {}

func (x *GetRoleToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleToolsRequest.ProtoReflect.Descriptor instead.
func (*GetRoleToolsRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleToolsRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

type GetRoleToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolInfo            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleToolsResponse) Reset() {
	*x = GetRoleToolsResponse{}
	mi := &file_tac_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleToolsResponse) ProtoMessage() {}

func (x *GetRoleToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleToolsResponse.ProtoReflect.Descriptor instead.
func (*GetRoleToolsResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{9}
}

func (x *GetRoleToolsResponse) GetTools() []*ToolInfo {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Language            string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Version             string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Dependencies        []string               `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	RequiresCompilation bool                   `protobuf:"varint,6,opt,name=requires_compilation,json=requiresCompilation,proto3" json:"requires_compilation,omitempty"`
	IsBinary            bool                   `protobuf:"varint,7,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	SourceAvailable     bool                   `protobuf:"varint,8,opt,name=source_available,json=sourceAvailable,proto3" json:"source_available,omitempty"`
	RuntimeRequirement  string                 `protobuf:"bytes,9,opt,name=runtime_requirement,json=runtimeRequirement,proto3" json:"runtime_requirement,omitempty"`
	Files               []string               `protobuf:"bytes,10,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ToolInfo) Reset() {
	*x = ToolInfo{}
	mi := &file_tac_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolInfo) ProtoMessage() {}

func (x *ToolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolInfo.ProtoReflect.Descriptor instead.
func (*ToolInfo) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{10}
}

func (x *ToolInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ToolInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ToolInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ToolInfo) GetRequiresCompilation() bool {
	if x != nil {
		return x.RequiresCompilation
	}
	return false
}

func (x *ToolInfo) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *ToolInfo) GetSourceAvailable() bool {
	if x != nil {
		return x.SourceAvailable
	}
	return false
}

func (x *ToolInfo) GetRuntimeRequirement() string {
	if x != nil {
		return x.RuntimeRequirement
	}
	return ""
}

func (x *ToolInfo) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	ToolName      string                 `protobuf:"bytes,5,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,6,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolArguments string                 `protobuf:"bytes,7,opt,name=tool_arguments,json=toolArguments,proto3" json:"tool_arguments,omitempty"`
	ToolResult    string                 `protobuf:"bytes,8,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	IsHistory     bool                   `protobuf:"varint,9,opt,name=is_history,json=isHistory,proto3" json:"is_history,omitempty"`
	EndOfTurn     bool                   `protobuf:"varint,10,opt,name=end_of_turn,json=endOfTurn,proto3" json:"end_of_turn,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,11,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RoleName      string                 `protobuf:"bytes,12,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,13,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageMode   string                 `protobuf:"bytes,15,opt,name=message_mode,json=messageMode,proto3" json:"message_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_tac_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{11}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *ChatMessage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ChatMessage) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ChatMessage) GetToolArguments() string {
	if x != nil {
		return x.ToolArguments
	}
	return ""
}

func (x *ChatMessage) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *ChatMessage) GetIsHistory() bool {
	if x != nil {
		return x.IsHistory
	}
	return false
}

func (x *ChatMessage) GetEndOfTurn() bool {
	if x != nil {
		return x.EndOfTurn
	}
	return false
}

func (x *ChatMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ChatMessage) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChatMessage) GetMessageMode() string {
	if x != nil {
		return x.MessageMode
	}
	return ""
}

type DownloadToolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ToolName       string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	DownloadSource bool                   `protobuf:"varint,2,opt,name=download_source,json=downloadSource,proto3" json:"download_source,omitempty"`
	DownloadBinary bool                   `protobuf:"varint,3,opt,name=download_binary,json=downloadBinary,proto3" json:"download_binary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadToolRequest) Reset() {
	*x = DownloadToolRequest{}
	mi := &file_tac_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadToolRequest) ProtoMessage() {}

func (x *DownloadToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadToolRequest.ProtoReflect.Descriptor instead.
func (*DownloadToolRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *DownloadToolRequest) GetDownloadSource() bool {
	if x != nil {
		return x.DownloadSource
	}
	return false
}

func (x *DownloadToolRequest) GetDownloadBinary() bool {
	if x != nil {
		return x.DownloadBinary
	}
	return false
}

type ToolChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FileName       string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	IsSource       bool                   `protobuf:"varint,3,opt,name=is_source,json=isSource,proto3" json:"is_source,omitempty"`
	IsLast         bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	IsLastFile     bool                   `protobuf:"varint,5,opt,name=is_last_file,json=isLastFile,proto3" json:"is_last_file,omitempty"`
	WarningMessage string                 `protobuf:"bytes,6,opt,name=warning_message,json=warningMessage,proto3" json:"warning_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolChunk) Reset() {
	*x = ToolChunk{}
	mi := &file_tac_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolChunk) ProtoMessage() {}

func (x *ToolChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolChunk.ProtoReflect.Descriptor instead.
func (*ToolChunk) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{13}
}

func (x *ToolChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ToolChunk) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ToolChunk) GetIsSource() bool {
	if x != nil {
		return x.IsSource
	}
	return false
}

func (x *ToolChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *ToolChunk) GetIsLastFile() bool {
	if x != nil {
		return x.IsLastFile
	}
	return false
}

func (x *ToolChunk) GetWarningMessage() string {
	if x != nil {
		return x.WarningMessage
	}
	return ""
}

type DaemonPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPingRequest) Reset() {
	*x = DaemonPingRequest{}
	mi := &file_tac_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPingRequest) ProtoMessage() {}

func (x *DaemonPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPingRequest.ProtoReflect.Descriptor instead.
func (*DaemonPingRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{14}
}

type DaemonPingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DaemonVersion   string                 `protobuf:"bytes,1,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	Workspace       string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	RunningTriggers int32                  `protobuf:"varint,3,opt,name=running_triggers,json=runningTriggers,proto3" json:"running_triggers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DaemonPingResponse) Reset() {
	*x = DaemonPingResponse{}
	mi := &file_tac_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPingResponse) ProtoMessage() {}

func (x *DaemonPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPingResponse.ProtoReflect.Descriptor instead.
func (*DaemonPingResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{15}
}

func (x *DaemonPingResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *DaemonPingResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DaemonPingResponse) GetRunningTriggers() int32 {
	if x != nil {
		return x.RunningTriggers
	}
	return 0
}

type TriggerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TriggerId     string                 `protobuf:"bytes,1,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIDRequest) Reset() {
	*x = TriggerIDRequest{}
	mi := &file_tac_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIDRequest) ProtoMessage() {}

func (x *TriggerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIDRequest.ProtoReflect.Descriptor instead.
func (*TriggerIDRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerIDRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_tac_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_tac_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{18}
}

type TriggerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggers      []*DaemonTrigger       `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerListResponse) Reset() {
	*x = TriggerListResponse{}
	mi := &file_tac_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerListResponse) ProtoMessage() {}

func (x *TriggerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerListResponse.ProtoReflect.Descriptor instead.
func (*TriggerListResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{19}
}

func (x *TriggerListResponse) GetTriggers() []*DaemonTrigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

type EventListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*DaemonEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventListResponse) Reset() {
	*x = EventListResponse{}
	mi := &file_tac_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventListResponse) ProtoMessage() {}

func (x *EventListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventListResponse.ProtoReflect.Descriptor instead.
func (*EventListResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{20}
}

func (x *EventListResponse) GetEvents() []*DaemonEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type DaemonTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TriggerType   string                 `protobuf:"bytes,3,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Running       bool                   `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	EventCount    int32                  `protobuf:"varint,7,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	Interval      string                 `protobuf:"bytes,8,opt,name=interval,proto3" json:"interval,omitempty"`
	CronExpr      string                 `protobuf:"bytes,9,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WatchPath     string                 `protobuf:"bytes,10,opt,name=watch_path,json=watchPath,proto3" json:"watch_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonTrigger) Reset() {
	*x = DaemonTrigger{}
	mi := &file_tac_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonTrigger) ProtoMessage() {}

func (x *DaemonTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonTrigger.ProtoReflect.Descriptor instead.
func (*DaemonTrigger) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{21}
}

func (x *DaemonTrigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DaemonTrigger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaemonTrigger) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *DaemonTrigger) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DaemonTrigger) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DaemonTrigger) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonTrigger) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *DaemonTrigger) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *DaemonTrigger) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *DaemonTrigger) GetWatchPath() string {
	if x != nil {
		return x.WatchPath
	}
	return ""
}

type DaemonEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoleKey       string                 `protobuf:"bytes,3,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	SessionMode   string                 `protobuf:"bytes,4,opt,name=session_mode,json=sessionMode,proto3" json:"session_mode,omitempty"`
	EnvCount      int32                  `protobuf:"varint,5,opt,name=env_count,json=envCount,proto3" json:"env_count,omitempty"`
	EnvPreset     string                 `protobuf:"bytes,6,opt,name=env_preset,json=envPreset,proto3" json:"env_preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonEvent) Reset() {
	*x = DaemonEvent{}
	mi := &file_tac_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonEvent) ProtoMessage() {}

func (x *DaemonEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonEvent.ProtoReflect.Descriptor instead.
func (*DaemonEvent) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{22}
}

func (x *DaemonEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DaemonEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DaemonEvent) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *DaemonEvent) GetSessionMode() string {
	if x != nil {
		return x.SessionMode
	}
	return ""
}

func (x *DaemonEvent) GetEnvCount() int32 {
	if x != nil {
		return x.EnvCount
	}
	return 0
}

func (x *DaemonEvent) GetEnvPreset() string {
	if x != nil {
		return x.EnvPreset
	}
	return ""
}

type DaemonStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Running             bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Workspace           string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	TriggerCount        int32                  `protobuf:"varint,3,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`
	EventCount          int32                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	RunningTriggerCount int32                  `protobuf:"varint,5,opt,name=running_trigger_count,json=runningTriggerCount,proto3" json:"running_trigger_count,omitempty"`
	Uptime              string                 `protobuf:"bytes,6,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DaemonStatusResponse) Reset() {
	*x = DaemonStatusResponse{}
	mi := &file_tac_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusResponse) ProtoMessage() {}

func (x *DaemonStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusResponse.ProtoReflect.Descriptor instead.
func (*DaemonStatusResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{23}
}

func (x *DaemonStatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonStatusResponse) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *DaemonStatusResponse) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *DaemonStatusResponse) GetEventCount() int32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *DaemonStatusResponse) GetRunningTriggerCount() int32 {
	if x != nil {
		return x.RunningTriggerCount
	}
	return 0
}

func (x *DaemonStatusResponse) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type CreateTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TriggerType   string                 `protobuf:"bytes,3,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Interval      string                 `protobuf:"bytes,5,opt,name=interval,proto3" json:"interval,omitempty"`
	CronExpr      string                 `protobuf:"bytes,6,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WatchPath     string                 `protobuf:"bytes,7,opt,name=watch_path,json=watchPath,proto3" json:"watch_path,omitempty"`
	Recursive     bool                   `protobuf:"varint,8,opt,name=recursive,proto3" json:"recursive,omitempty"`
	EventIds      []string               `protobuf:"bytes,9,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTriggerRequest) Reset() {
	*x = CreateTriggerRequest{}
	mi := &file_tac_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTriggerRequest) ProtoMessage() {}

func (x *CreateTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTriggerRequest.ProtoReflect.Descriptor instead.
func (*CreateTriggerRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{24}
}

func (x *CreateTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTriggerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTriggerRequest) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *CreateTriggerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTriggerRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *CreateTriggerRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateTriggerRequest) GetWatchPath() string {
	if x != nil {
		return x.WatchPath
	}
	return ""
}

func (x *CreateTriggerRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CreateTriggerRequest) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type UpdateTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Interval      string                 `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WatchPath     string                 `protobuf:"bytes,6,opt,name=watch_path,json=watchPath,proto3" json:"watch_path,omitempty"`
	Recursive     bool                   `protobuf:"varint,7,opt,name=recursive,proto3" json:"recursive,omitempty"`
	EventIds      []string               `protobuf:"bytes,8,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTriggerRequest) Reset() {
	*x = UpdateTriggerRequest{}
	mi := &file_tac_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTriggerRequest) ProtoMessage() {}

func (x *UpdateTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTriggerRequest.ProtoReflect.Descriptor instead.
func (*UpdateTriggerRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTriggerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTriggerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTriggerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTriggerRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *UpdateTriggerRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *UpdateTriggerRequest) GetWatchPath() string {
	if x != nil {
		return x.WatchPath
	}
	return ""
}

func (x *UpdateTriggerRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *UpdateTriggerRequest) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RoleKey       string                 `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	InitialMsg    string                 `protobuf:"bytes,5,opt,name=initial_msg,json=initialMsg,proto3" json:"initial_msg,omitempty"`
	SessionMode   string                 `protobuf:"bytes,6,opt,name=session_mode,json=sessionMode,proto3" json:"session_mode,omitempty"`
	MessageMode   string                 `protobuf:"bytes,7,opt,name=message_mode,json=messageMode,proto3" json:"message_mode,omitempty"`
	Env           map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvPreset     string                 `protobuf:"bytes,9,opt,name=env_preset,json=envPreset,proto3" json:"env_preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_tac_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{26}
}

func (x *CreateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *CreateEventRequest) GetInitialMsg() string {
	if x != nil {
		return x.InitialMsg
	}
	return ""
}

func (x *CreateEventRequest) GetSessionMode() string {
	if x != nil {
		return x.SessionMode
	}
	return ""
}

func (x *CreateEventRequest) GetMessageMode() string {
	if x != nil {
		return x.MessageMode
	}
	return ""
}

func (x *CreateEventRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateEventRequest) GetEnvPreset() string {
	if x != nil {
		return x.EnvPreset
	}
	return ""
}

type UpdateEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RoleKey        string                 `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	InitialMsg     string                 `protobuf:"bytes,5,opt,name=initial_msg,json=initialMsg,proto3" json:"initial_msg,omitempty"`
	SessionMode    string                 `protobuf:"bytes,6,opt,name=session_mode,json=sessionMode,proto3" json:"session_mode,omitempty"`
	MessageMode    string                 `protobuf:"bytes,7,opt,name=message_mode,json=messageMode,proto3" json:"message_mode,omitempty"`
	Env            map[string]string      `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnvPreset      string                 `protobuf:"bytes,9,opt,name=env_preset,json=envPreset,proto3" json:"env_preset,omitempty"`
	SetMessageMode bool                   `protobuf:"varint,10,opt,name=set_message_mode,json=setMessageMode,proto3" json:"set_message_mode,omitempty"`
	SetEnvPreset   bool                   `protobuf:"varint,11,opt,name=set_env_preset,json=setEnvPreset,proto3" json:"set_env_preset,omitempty"`
	SetEnv         bool                   `protobuf:"varint,12,opt,name=set_env,json=setEnv,proto3" json:"set_env,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_tac_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *UpdateEventRequest) GetInitialMsg() string {
	if x != nil {
		return x.InitialMsg
	}
	return ""
}

func (x *UpdateEventRequest) GetSessionMode() string {
	if x != nil {
		return x.SessionMode
	}
	return ""
}

func (x *UpdateEventRequest) GetMessageMode() string {
	if x != nil {
		return x.MessageMode
	}
	return ""
}

func (x *UpdateEventRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UpdateEventRequest) GetEnvPreset() string {
	if x != nil {
		return x.EnvPreset
	}
	return ""
}

func (x *UpdateEventRequest) GetSetMessageMode() bool {
	if x != nil {
		return x.SetMessageMode
	}
	return false
}

func (x *UpdateEventRequest) GetSetEnvPreset() bool {
	if x != nil {
		return x.SetEnvPreset
	}
	return false
}

func (x *UpdateEventRequest) GetSetEnv() bool {
	if x != nil {
		return x.SetEnv
	}
	return false
}

type EventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventIDRequest) Reset() {
	*x = EventIDRequest{}
	mi := &file_tac_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventIDRequest) ProtoMessage() {}

func (x *EventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventIDRequest.ProtoReflect.Descriptor instead.
func (*EventIDRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{28}
}

func (x *EventIDRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_tac_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{29}
}

func (x *EventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnvPreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvPreset) Reset() {
	*x = EnvPreset{}
	mi := &file_tac_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPreset) ProtoMessage() {}

func (x *EnvPreset) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPreset.ProtoReflect.Descriptor instead.
func (*EnvPreset) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{30}
}

func (x *EnvPreset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvPreset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EnvPreset) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *EnvPreset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EnvPreset) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EnvPresetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*EnvPreset           `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvPresetListResponse) Reset() {
	*x = EnvPresetListResponse{}
	mi := &file_tac_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvPresetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPresetListResponse) ProtoMessage() {}

func (x *EnvPresetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPresetListResponse.ProtoReflect.Descriptor instead.
func (*EnvPresetListResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{31}
}

func (x *EnvPresetListResponse) GetPresets() []*EnvPreset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type CreateEnvPresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvPresetRequest) Reset() {
	*x = CreateEnvPresetRequest{}
	mi := &file_tac_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvPresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvPresetRequest) ProtoMessage() {}

func (x *CreateEnvPresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvPresetRequest.ProtoReflect.Descriptor instead.
func (*CreateEnvPresetRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{32}
}

func (x *CreateEnvPresetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEnvPresetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEnvPresetRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type UpdateEnvPresetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Env            map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SetDescription bool                   `protobuf:"varint,4,opt,name=set_description,json=setDescription,proto3" json:"set_description,omitempty"`
	SetEnv         bool                   `protobuf:"varint,5,opt,name=set_env,json=setEnv,proto3" json:"set_env,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateEnvPresetRequest) Reset() {
	*x = UpdateEnvPresetRequest{}
	mi := &file_tac_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvPresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvPresetRequest) ProtoMessage() {}

func (x *UpdateEnvPresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvPresetRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvPresetRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateEnvPresetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEnvPresetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateEnvPresetRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UpdateEnvPresetRequest) GetSetDescription() bool {
	if x != nil {
		return x.SetDescription
	}
	return false
}

func (x *UpdateEnvPresetRequest) GetSetEnv() bool {
	if x != nil {
		return x.SetEnv
	}
	return false
}

type EnvPresetIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvPresetIDRequest) Reset() {
	*x = EnvPresetIDRequest{}
	mi := &file_tac_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvPresetIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPresetIDRequest) ProtoMessage() {}

func (x *EnvPresetIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPresetIDRequest.ProtoReflect.Descriptor instead.
func (*EnvPresetIDRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{34}
}

func (x *EnvPresetIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EnvPresetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvPresetResponse) Reset() {
	*x = EnvPresetResponse{}
	mi := &file_tac_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvPresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvPresetResponse) ProtoMessage() {}

func (x *EnvPresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvPresetResponse.ProtoReflect.Descriptor instead.
func (*EnvPresetResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{35}
}

func (x *EnvPresetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnvPresetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActiveSessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	RoleName      string                 `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	TriggerId     string                 `protobuf:"bytes,4,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	EventId       string                 `protobuf:"bytes,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StartTimeUnix int64                  `protobuf:"varint,6,opt,name=start_time_unix,json=startTimeUnix,proto3" json:"start_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSessionInfo) Reset() {
	*x = ActiveSessionInfo{}
	mi := &file_tac_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSessionInfo) ProtoMessage() {}

func (x *ActiveSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSessionInfo.ProtoReflect.Descriptor instead.
func (*ActiveSessionInfo) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{36}
}

func (x *ActiveSessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ActiveSessionInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ActiveSessionInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ActiveSessionInfo) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *ActiveSessionInfo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ActiveSessionInfo) GetStartTimeUnix() int64 {
	if x != nil {
		return x.StartTimeUnix
	}
	return 0
}

type ActiveSessionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*ActiveSessionInfo   `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveSessionListResponse) Reset() {
	*x = ActiveSessionListResponse{}
	mi := &file_tac_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveSessionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveSessionListResponse) ProtoMessage() {}

func (x *ActiveSessionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveSessionListResponse.ProtoReflect.Descriptor instead.
func (*ActiveSessionListResponse) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{37}
}

func (x *ActiveSessionListResponse) GetSessions() []*ActiveSessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type WatchSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionRequest) Reset() {
	*x = WatchSessionRequest{}
	mi := &file_tac_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionRequest) ProtoMessage() {}

func (x *WatchSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tac_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionRequest) Descriptor() ([]byte, []int) {
	return file_tac_proto_rawDescGZIP(), []int{38}
}

func (x *WatchSessionRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *WatchSessionRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *WatchSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_tac_proto protoreflect.FileDescriptor

const file_tac_proto_rawDesc = "" +
	"\n" +
	"\ttac.proto\x12\x03tac\"4\n" +
	"\vPingRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"\x8f\x01\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x127\n" +
	"\x17certificate_fingerprint\x18\x03 \x01(\tR\x16certificateFingerprint\"\x13\n" +
	"\x11ServerInfoRequest\"\xbb\x01\n" +
	"\x12ServerInfoResponse\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x1d\n" +
	"\n" +
	"role_count\x18\x03 \x01(\x05R\troleCount\x12\x1d\n" +
	"\n" +
	"tool_count\x18\x04 \x01(\x05R\ttoolCount\x12\x1f\n" +
	"\vapi_version\x18\x05 \x01(\tR\n" +
	"apiVersion\"\x12\n" +
	"\x10ListRolesRequest\"4\n" +
	"\x11ListRolesResponse\x12\x1f\n" +
	"\x05roles\x18\x01 \x03(\v2\t.tac.RoleR\x05roles\"$\n" +
	"\x0eGetRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xe2\x02\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"components\x18\x03 \x03(\tR\n" +
	"components\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12$\n" +
	"\x03env\x18\x05 \x03(\v2\x12.tac.Role.EnvEntryR\x03env\x12\x19\n" +
	"\bapi_type\x18\x06 \x01(\tR\aapiType\x12!\n" +
	"\fmessage_mode\x18\a \x01(\tR\vmessageMode\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x14\n" +
	"\x05model\x18\n" +
	" \x01(\tR\x05model\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x13GetRoleToolsRequest\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\";\n" +
	"\x14GetRoleToolsResponse\x12#\n" +
	"\x05tools\x18\x01 \x03(\v2\r.tac.ToolInfoR\x05tools\"\xdc\x02\n" +
	"\bToolInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fdependencies\x18\x05 \x03(\tR\fdependencies\x121\n" +
	"\x14requires_compilation\x18\x06 \x01(\bR\x13requiresCompilation\x12\x1b\n" +
	"\tis_binary\x18\a \x01(\bR\bisBinary\x12)\n" +
	"\x10source_available\x18\b \x01(\bR\x0fsourceAvailable\x12/\n" +
	"\x13runtime_requirement\x18\t \x01(\tR\x12runtimeRequirement\x12\x14\n" +
	"\x05files\x18\n" +
	" \x03(\tR\x05files\"\xe5\x03\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x1b\n" +
	"\ttool_name\x18\x05 \x01(\tR\btoolName\x12 \n" +
	"\ftool_call_id\x18\x06 \x01(\tR\n" +
	"toolCallId\x12%\n" +
	"\x0etool_arguments\x18\a \x01(\tR\rtoolArguments\x12\x1f\n" +
	"\vtool_result\x18\b \x01(\tR\n" +
	"toolResult\x12\x1d\n" +
	"\n" +
	"is_history\x18\t \x01(\bR\tisHistory\x12\x1e\n" +
	"\vend_of_turn\x18\n" +
	" \x01(\bR\tendOfTurn\x12#\n" +
	"\rerror_message\x18\v \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\trole_name\x18\f \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"session_id\x18\r \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x0e \x01(\tR\ttimestamp\x12!\n" +
	"\fmessage_mode\x18\x0f \x01(\tR\vmessageMode\"\x84\x01\n" +
	"\x13DownloadToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12'\n" +
	"\x0fdownload_source\x18\x02 \x01(\bR\x0edownloadSource\x12'\n" +
	"\x0fdownload_binary\x18\x03 \x01(\bR\x0edownloadBinary\"\xbd\x01\n" +
	"\tToolChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tis_source\x18\x03 \x01(\bR\bisSource\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\x12 \n" +
	"\fis_last_file\x18\x05 \x01(\bR\n" +
	"isLastFile\x12'\n" +
	"\x0fwarning_message\x18\x06 \x01(\tR\x0ewarningMessage\"\x13\n" +
	"\x11DaemonPingRequest\"\x84\x01\n" +
	"\x12DaemonPingResponse\x12%\n" +
	"\x0edaemon_version\x18\x01 \x01(\tR\rdaemonVersion\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12)\n" +
	"\x10running_triggers\x18\x03 \x01(\x05R\x0frunningTriggers\"1\n" +
	"\x10TriggerIDRequest\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x01 \x01(\tR\ttriggerId\"E\n" +
	"\x0fTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"E\n" +
	"\x13TriggerListResponse\x12.\n" +
	"\btriggers\x18\x01 \x03(\v2\x12.tac.DaemonTriggerR\btriggers\"=\n" +
	"\x11EventListResponse\x12(\n" +
	"\x06events\x18\x01 \x03(\v2\x10.tac.DaemonEventR\x06events\"\xa5\x02\n" +
	"\rDaemonTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ftrigger_type\x18\x03 \x01(\tR\vtriggerType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x18\n" +
	"\arunning\x18\x06 \x01(\bR\arunning\x12\x1f\n" +
	"\vevent_count\x18\a \x01(\x05R\n" +
	"eventCount\x12\x1a\n" +
	"\binterval\x18\b \x01(\tR\binterval\x12\x1b\n" +
	"\tcron_expr\x18\t \x01(\tR\bcronExpr\x12\x1d\n" +
	"\n" +
	"watch_path\x18\n" +
	" \x01(\tR\twatchPath\"\xab\x01\n" +
	"\vDaemonEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\brole_key\x18\x03 \x01(\tR\aroleKey\x12!\n" +
	"\fsession_mode\x18\x04 \x01(\tR\vsessionMode\x12\x1b\n" +
	"\tenv_count\x18\x05 \x01(\x05R\benvCount\x12\x1d\n" +
	"\n" +
	"env_preset\x18\x06 \x01(\tR\tenvPreset\"\xe0\x01\n" +
	"\x14DaemonStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\x12#\n" +
	"\rtrigger_count\x18\x03 \x01(\x05R\ftriggerCount\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x05R\n" +
	"eventCount\x122\n" +
	"\x15running_trigger_count\x18\x05 \x01(\x05R\x13runningTriggerCount\x12\x16\n" +
	"\x06uptime\x18\x06 \x01(\tR\x06uptime\"\x92\x02\n" +
	"\x14CreateTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ftrigger_type\x18\x03 \x01(\tR\vtriggerType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\binterval\x18\x05 \x01(\tR\binterval\x12\x1b\n" +
	"\tcron_expr\x18\x06 \x01(\tR\bcronExpr\x12\x1d\n" +
	"\n" +
	"watch_path\x18\a \x01(\tR\twatchPath\x12\x1c\n" +
	"\trecursive\x18\b \x01(\bR\trecursive\x12\x1b\n" +
	"\tevent_ids\x18\t \x03(\tR\beventIds\"\xef\x01\n" +
	"\x14UpdateTriggerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\tR\binterval\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12\x1d\n" +
	"\n" +
	"watch_path\x18\x06 \x01(\tR\twatchPath\x12\x1c\n" +
	"\trecursive\x18\a \x01(\bR\trecursive\x12\x1b\n" +
	"\tevent_ids\x18\b \x03(\tR\beventIds\"\xe7\x02\n" +
	"\x12CreateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\brole_key\x18\x04 \x01(\tR\aroleKey\x12\x1f\n" +
	"\vinitial_msg\x18\x05 \x01(\tR\n" +
	"initialMsg\x12!\n" +
	"\fsession_mode\x18\x06 \x01(\tR\vsessionMode\x12!\n" +
	"\fmessage_mode\x18\a \x01(\tR\vmessageMode\x122\n" +
	"\x03env\x18\b \x03(\v2 .tac.CreateEventRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"env_preset\x18\t \x01(\tR\tenvPreset\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x03\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\brole_key\x18\x04 \x01(\tR\aroleKey\x12\x1f\n" +
	"\vinitial_msg\x18\x05 \x01(\tR\n" +
	"initialMsg\x12!\n" +
	"\fsession_mode\x18\x06 \x01(\tR\vsessionMode\x12!\n" +
	"\fmessage_mode\x18\a \x01(\tR\vmessageMode\x122\n" +
	"\x03env\x18\b \x03(\v2 .tac.UpdateEventRequest.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"env_preset\x18\t \x01(\tR\tenvPreset\x12(\n" +
	"\x10set_message_mode\x18\n" +
	" \x01(\bR\x0esetMessageMode\x12$\n" +
	"\x0eset_env_preset\x18\v \x01(\bR\fsetEnvPreset\x12\x17\n" +
	"\aset_env\x18\f \x01(\bR\x06setEnv\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x0eEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"C\n" +
	"\rEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x01\n" +
	"\tEnvPreset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12)\n" +
	"\x03env\x18\x03 \x03(\v2\x17.tac.EnvPreset.EnvEntryR\x03env\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x15EnvPresetListResponse\x12(\n" +
	"\apresets\x18\x01 \x03(\v2\x0e.tac.EnvPresetR\apresets\"\xbe\x01\n" +
	"\x16CreateEnvPresetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.tac.CreateEnvPresetRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x16UpdateEnvPresetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.tac.UpdateEnvPresetRequest.EnvEntryR\x03env\x12'\n" +
	"\x0fset_description\x18\x04 \x01(\bR\x0esetDescription\x12\x17\n" +
	"\aset_env\x18\x05 \x01(\bR\x06setEnv\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x12EnvPresetIDRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x11EnvPresetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\x11ActiveSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\trole_name\x18\x03 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x04 \x01(\tR\ttriggerId\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\tR\aeventId\x12&\n" +
	"\x0fstart_time_unix\x18\x06 \x01(\x03R\rstartTimeUnix\"O\n" +
	"\x19ActiveSessionListResponse\x122\n" +
	"\bsessions\x18\x01 \x03(\v2\x16.tac.ActiveSessionInfoR\bsessions\"r\n" +
	"\x13WatchSessionRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId2\xad\x02\n" +
	"\x10DiscoveryService\x12+\n" +
	"\x04Ping\x12\x10.tac.PingRequest\x1a\x11.tac.PingResponse\x12@\n" +
	"\rGetServerInfo\x12\x16.tac.ServerInfoRequest\x1a\x17.tac.ServerInfoResponse\x12:\n" +
	"\tListRoles\x12\x15.tac.ListRolesRequest\x1a\x16.tac.ListRolesResponse\x12)\n" +
	"\aGetRole\x12\x13.tac.GetRoleRequest\x1a\t.tac.Role\x12C\n" +
	"\fGetRoleTools\x12\x18.tac.GetRoleToolsRequest\x1a\x19.tac.GetRoleToolsResponse2=\n" +
	"\vChatService\x12.\n" +
	"\x04Chat\x12\x10.tac.ChatMessage\x1a\x10.tac.ChatMessage(\x010\x012I\n" +
	"\vToolService\x12:\n" +
	"\fDownloadTool\x12\x18.tac.DownloadToolRequest\x1a\x0e.tac.ToolChunk0\x012\x85\n" +
	"\n" +
	"\rDaemonService\x127\n" +
	"\x04Ping\x12\x16.tac.DaemonPingRequest\x1a\x17.tac.DaemonPingResponse\x12;\n" +
	"\fStartTrigger\x12\x15.tac.TriggerIDRequest\x1a\x14.tac.TriggerResponse\x12:\n" +
	"\vStopTrigger\x12\x15.tac.TriggerIDRequest\x1a\x14.tac.TriggerResponse\x129\n" +
	"\n" +
	"RunTrigger\x12\x15.tac.TriggerIDRequest\x1a\x14.tac.TriggerResponse\x124\n" +
	"\fListTriggers\x12\n" +
	".tac.Empty\x1a\x18.tac.TriggerListResponse\x120\n" +
	"\n" +
	"ListEvents\x12\n" +
	".tac.Empty\x1a\x16.tac.EventListResponse\x12A\n" +
	"\x10GetTriggerEvents\x12\x15.tac.TriggerIDRequest\x1a\x16.tac.EventListResponse\x12@\n" +
	"\rCreateTrigger\x12\x19.tac.CreateTriggerRequest\x1a\x14.tac.TriggerResponse\x12@\n" +
	"\rUpdateTrigger\x12\x19.tac.UpdateTriggerRequest\x1a\x14.tac.TriggerResponse\x12<\n" +
	"\rDeleteTrigger\x12\x15.tac.TriggerIDRequest\x1a\x14.tac.TriggerResponse\x12:\n" +
	"\vCreateEvent\x12\x17.tac.CreateEventRequest\x1a\x12.tac.EventResponse\x12:\n" +
	"\vUpdateEvent\x12\x17.tac.UpdateEventRequest\x1a\x12.tac.EventResponse\x126\n" +
	"\vDeleteEvent\x12\x13.tac.EventIDRequest\x1a\x12.tac.EventResponse\x128\n" +
	"\x0eListEnvPresets\x12\n" +
	".tac.Empty\x1a\x1a.tac.EnvPresetListResponse\x12F\n" +
	"\x0fCreateEnvPreset\x12\x1b.tac.CreateEnvPresetRequest\x1a\x16.tac.EnvPresetResponse\x12F\n" +
	"\x0fUpdateEnvPreset\x12\x1b.tac.UpdateEnvPresetRequest\x1a\x16.tac.EnvPresetResponse\x12B\n" +
	"\x0fDeleteEnvPreset\x12\x17.tac.EnvPresetIDRequest\x1a\x16.tac.EnvPresetResponse\x128\n" +
	"\x0fGetDaemonStatus\x12\n" +
	".tac.Empty\x1a\x19.tac.DaemonStatusResponse\x12\"\n" +
	"\bShutdown\x12\n" +
	".tac.Empty\x1a\n" +
	".tac.Empty\x12@\n" +
	"\x12ListActiveSessions\x12\n" +
	".tac.Empty\x1a\x1e.tac.ActiveSessionListResponse\x12<\n" +
	"\fWatchSession\x12\x18.tac.WatchSessionRequest\x1a\x10.tac.ChatMessage0\x01B\x1dZ\x1bgithub.com/Lyoomu/TAC/protob\x06proto3"

var (
	file_tac_proto_rawDescOnce sync.Once
	file_tac_proto_rawDescData []byte
)

func file_tac_proto_rawDescGZIP() []byte {
	file_tac_proto_rawDescOnce.Do(func() {
		file_tac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tac_proto_rawDesc), len(file_tac_proto_rawDesc)))
	})
	return file_tac_proto_rawDescData
}

var file_tac_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_tac_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: tac.PingRequest
	(*PingResponse)(nil),              // 1: tac.PingResponse
	(*ServerInfoRequest)(nil),         // 2: tac.ServerInfoRequest
	(*ServerInfoResponse)(nil),        // 3: tac.ServerInfoResponse
	(*ListRolesRequest)(nil),          // 4: tac.ListRolesRequest
	(*ListRolesResponse)(nil),         // 5: tac.ListRolesResponse
	(*GetRoleRequest)(nil),            // 6: tac.GetRoleRequest
	(*Role)(nil),                      // 7: tac.Role
	(*GetRoleToolsRequest)(nil),       // 8: tac.GetRoleToolsRequest
	(*GetRoleToolsResponse)(nil),      // 9: tac.GetRoleToolsResponse
	(*ToolInfo)(nil),                  // 10: tac.ToolInfo
	(*ChatMessage)(nil),               // 11: tac.ChatMessage
	(*DownloadToolRequest)(nil),       // 12: tac.DownloadToolRequest
	(*ToolChunk)(nil),                 // 13: tac.ToolChunk
	(*DaemonPingRequest)(nil),         // 14: tac.DaemonPingRequest
	(*DaemonPingResponse)(nil),        // 15: tac.DaemonPingResponse
	(*TriggerIDRequest)(nil),          // 16: tac.TriggerIDRequest
	(*TriggerResponse)(nil),           // 17: tac.TriggerResponse
	(*Empty)(nil),                     // 18: tac.Empty
	(*TriggerListResponse)(nil),       // 19: tac.TriggerListResponse
	(*EventListResponse)(nil),         // 20: tac.EventListResponse
	(*DaemonTrigger)(nil),             // 21: tac.DaemonTrigger
	(*DaemonEvent)(nil),               // 22: tac.DaemonEvent
	(*DaemonStatusResponse)(nil),      // 23: tac.DaemonStatusResponse
	(*CreateTriggerRequest)(nil),      // 24: tac.CreateTriggerRequest
	(*UpdateTriggerRequest)(nil),      // 25: tac.UpdateTriggerRequest
	(*CreateEventRequest)(nil),        // 26: tac.CreateEventRequest
	(*UpdateEventRequest)(nil),        // 27: tac.UpdateEventRequest
	(*EventIDRequest)(nil),            // 28: tac.EventIDRequest
	(*EventResponse)(nil),             // 29: tac.EventResponse
	(*EnvPreset)(nil),                 // 30: tac.EnvPreset
	(*EnvPresetListResponse)(nil),     // 31: tac.EnvPresetListResponse
	(*CreateEnvPresetRequest)(nil),    // 32: tac.CreateEnvPresetRequest
	(*UpdateEnvPresetRequest)(nil),    // 33: tac.UpdateEnvPresetRequest
	(*EnvPresetIDRequest)(nil),        // 34: tac.EnvPresetIDRequest
	(*EnvPresetResponse)(nil),         // 35: tac.EnvPresetResponse
	(*ActiveSessionInfo)(nil),         // 36: tac.ActiveSessionInfo
	(*ActiveSessionListResponse)(nil), // 37: tac.ActiveSessionListResponse
	(*WatchSessionRequest)(nil),       // 38: tac.WatchSessionRequest
	nil,                               // 39: tac.Role.EnvEntry
	nil,                               // 40: tac.CreateEventRequest.EnvEntry
	nil,                               // 41: tac.UpdateEventRequest.EnvEntry
	nil,                               // 42: tac.EnvPreset.EnvEntry
	nil,                               // 43: tac.CreateEnvPresetRequest.EnvEntry
	nil,                               // 44: tac.UpdateEnvPresetRequest.EnvEntry
}
var file_tac_proto_depIdxs = []int32{
	7,  // 0: tac.ListRolesResponse.roles:type_name -> tac.Role
	39, // 1: tac.Role.env:type_name -> tac.Role.EnvEntry
	10, // 2: tac.GetRoleToolsResponse.tools:type_name -> tac.ToolInfo
	21, // 3: tac.TriggerListResponse.triggers:type_name -> tac.DaemonTrigger
	22, // 4: tac.EventListResponse.events:type_name -> tac.DaemonEvent
	40, // 5: tac.CreateEventRequest.env:type_name -> tac.CreateEventRequest.EnvEntry
	41, // 6: tac.UpdateEventRequest.env:type_name -> tac.UpdateEventRequest.EnvEntry
	42, // 7: tac.EnvPreset.env:type_name -> tac.EnvPreset.EnvEntry
	30, // 8: tac.EnvPresetListResponse.presets:type_name -> tac.EnvPreset
	43, // 9: tac.CreateEnvPresetRequest.env:type_name -> tac.CreateEnvPresetRequest.EnvEntry
	44, // 10: tac.UpdateEnvPresetRequest.env:type_name -> tac.UpdateEnvPresetRequest.EnvEntry
	36, // 11: tac.ActiveSessionListResponse.sessions:type_name -> tac.ActiveSessionInfo
	0,  // 12: tac.DiscoveryService.Ping:input_type -> tac.PingRequest
	2,  // 13: tac.DiscoveryService.GetServerInfo:input_type -> tac.ServerInfoRequest
	4,  // 14: tac.DiscoveryService.ListRoles:input_type -> tac.ListRolesRequest
	6,  // 15: tac.DiscoveryService.GetRole:input_type -> tac.GetRoleRequest
	8,  // 16: tac.DiscoveryService.GetRoleTools:input_type -> tac.GetRoleToolsRequest
	11, // 17: tac.ChatService.Chat:input_type -> tac.ChatMessage
	12, // 18: tac.ToolService.DownloadTool:input_type -> tac.DownloadToolRequest
	14, // 19: tac.DaemonService.Ping:input_type -> tac.DaemonPingRequest
	16, // 20: tac.DaemonService.StartTrigger:input_type -> tac.TriggerIDRequest
	16, // 21: tac.DaemonService.StopTrigger:input_type -> tac.TriggerIDRequest
	16, // 22: tac.DaemonService.RunTrigger:input_type -> tac.TriggerIDRequest
	18, // 23: tac.DaemonService.ListTriggers:input_type -> tac.Empty
	18, // 24: tac.DaemonService.ListEvents:input_type -> tac.Empty
	16, // 25: tac.DaemonService.GetTriggerEvents:input_type -> tac.TriggerIDRequest
	24, // 26: tac.DaemonService.CreateTrigger:input_type -> tac.CreateTriggerRequest
	25, // 27: tac.DaemonService.UpdateTrigger:input_type -> tac.UpdateTriggerRequest
	16, // 28: tac.DaemonService.DeleteTrigger:input_type -> tac.TriggerIDRequest
	26, // 29: tac.DaemonService.CreateEvent:input_type -> tac.CreateEventRequest
	27, // 30: tac.DaemonService.UpdateEvent:input_type -> tac.UpdateEventRequest
	28, // 31: tac.DaemonService.DeleteEvent:input_type -> tac.EventIDRequest
	18, // 32: tac.DaemonService.ListEnvPresets:input_type -> tac.Empty
	32, // 33: tac.DaemonService.CreateEnvPreset:input_type -> tac.CreateEnvPresetRequest
	33, // 34: tac.DaemonService.UpdateEnvPreset:input_type -> tac.UpdateEnvPresetRequest
	34, // 35: tac.DaemonService.DeleteEnvPreset:input_type -> tac.EnvPresetIDRequest
	18, // 36: tac.DaemonService.GetDaemonStatus:input_type -> tac.Empty
	18, // 37: tac.DaemonService.Shutdown:input_type -> tac.Empty
	18, // 38: tac.DaemonService.ListActiveSessions:input_type -> tac.Empty
	38, // 39: tac.DaemonService.WatchSession:input_type -> tac.WatchSessionRequest
	1,  // 40: tac.DiscoveryService.Ping:output_type -> tac.PingResponse
	3,  // 41: tac.DiscoveryService.GetServerInfo:output_type -> tac.ServerInfoResponse
	5,  // 42: tac.DiscoveryService.ListRoles:output_type -> tac.ListRolesResponse
	7,  // 43: tac.DiscoveryService.GetRole:output_type -> tac.Role
	9,  // 44: tac.DiscoveryService.GetRoleTools:output_type -> tac.GetRoleToolsResponse
	11, // 45: tac.ChatService.Chat:output_type -> tac.ChatMessage
	13, // 46: tac.ToolService.DownloadTool:output_type -> tac.ToolChunk
	15, // 47: tac.DaemonService.Ping:output_type -> tac.DaemonPingResponse
	17, // 48: tac.DaemonService.StartTrigger:output_type -> tac.TriggerResponse
	17, // 49: tac.DaemonService.StopTrigger:output_type -> tac.TriggerResponse
	17, // 50: tac.DaemonService.RunTrigger:output_type -> tac.TriggerResponse
	19, // 51: tac.DaemonService.ListTriggers:output_type -> tac.TriggerListResponse
	20, // 52: tac.DaemonService.ListEvents:output_type -> tac.EventListResponse
	20, // 53: tac.DaemonService.GetTriggerEvents:output_type -> tac.EventListResponse
	17, // 54: tac.DaemonService.CreateTrigger:output_type -> tac.TriggerResponse
	17, // 55: tac.DaemonService.UpdateTrigger:output_type -> tac.TriggerResponse
	17, // 56: tac.DaemonService.DeleteTrigger:output_type -> tac.TriggerResponse
	29, // 57: tac.DaemonService.CreateEvent:output_type -> tac.EventResponse
	29, // 58: tac.DaemonService.UpdateEvent:output_type -> tac.EventResponse
	29, // 59: tac.DaemonService.DeleteEvent:output_type -> tac.EventResponse
	31, // 60: tac.DaemonService.ListEnvPresets:output_type -> tac.EnvPresetListResponse
	35, // 61: tac.DaemonService.CreateEnvPreset:output_type -> tac.EnvPresetResponse
	35, // 62: tac.DaemonService.UpdateEnvPreset:output_type -> tac.EnvPresetResponse
	35, // 63: tac.DaemonService.DeleteEnvPreset:output_type -> tac.EnvPresetResponse
	23, // 64: tac.DaemonService.GetDaemonStatus:output_type -> tac.DaemonStatusResponse
	18, // 65: tac.DaemonService.Shutdown:output_type -> tac.Empty
	37, // 66: tac.DaemonService.ListActiveSessions:output_type -> tac.ActiveSessionListResponse
	11, // 67: tac.DaemonService.WatchSession:output_type -> tac.ChatMessage
	40, // [40:68] is the sub-list for method output_type
	12, // [12:40] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tac_proto_init() }
func file_tac_proto_init() {
	if File_tac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tac_proto_rawDesc), len(file_tac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_tac_proto_goTypes,
		DependencyIndexes: file_tac_proto_depIdxs,
		MessageInfos:      file_tac_proto_msgTypes,
	}.Build()
	File_tac_proto = out.File
	file_tac_proto_goTypes = nil
	file_tac_proto_depIdxs = nil
}
