// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: tac.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryService_Ping_FullMethodName          = "/tac.DiscoveryService/Ping"
	DiscoveryService_GetServerInfo_FullMethodName = "/tac.DiscoveryService/GetServerInfo"
	DiscoveryService_ListRoles_FullMethodName     = "/tac.DiscoveryService/ListRoles"
	DiscoveryService_GetRole_FullMethodName       = "/tac.DiscoveryService/GetRole"
	DiscoveryService_GetRoleTools_FullMethodName  = "/tac.DiscoveryService/GetRoleTools"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GetServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*Role, error)
	GetRoleTools(ctx context.Context, in *GetRoleToolsRequest, opts ...grpc.CallOption) (*GetRoleToolsResponse, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetRole(ctx context.Context, in *GetRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Role)
	err := c.cc.Invoke(ctx, DiscoveryService_GetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetRoleTools(ctx context.Context, in *GetRoleToolsRequest, opts ...grpc.CallOption) (*GetRoleToolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoleToolsResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GetRoleTools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
type DiscoveryServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GetServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	GetRole(context.Context, *GetRoleRequest) (*Role, error)
	GetRoleTools(context.Context, *GetRoleToolsRequest) (*GetRoleToolsResponse, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedDiscoveryServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetRole(context.Context, *GetRoleRequest) (*Role, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetRoleTools(context.Context, *GetRoleToolsRequest) (*GetRoleToolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoleTools not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetServerInfo(ctx, req.(*ServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetRole(ctx, req.(*GetRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetRoleTools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleToolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetRoleTools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetRoleTools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetRoleTools(ctx, req.(*GetRoleToolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tac.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DiscoveryService_Ping_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _DiscoveryService_GetServerInfo_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _DiscoveryService_ListRoles_Handler,
		},
		{
			MethodName: "GetRole",
			Handler:    _DiscoveryService_GetRole_Handler,
		},
		{
			MethodName: "GetRoleTools",
			Handler:    _DiscoveryService_GetRoleTools_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tac.proto",
}

const (
	ChatService_Chat_FullMethodName = "/tac.ChatService/Chat"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChatService_ServiceDesc.Streams[0], ChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatClient = grpc.BidiStreamingClient[ChatMessage, ChatMessage]

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) Chat(grpc.BidiStreamingServer[ChatMessage, ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Chat(&grpc.GenericServerStream[ChatMessage, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChatService_ChatServer = grpc.BidiStreamingServer[ChatMessage, ChatMessage]

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tac.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChatService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tac.proto",
}

const (
	ToolService_DownloadTool_FullMethodName = "/tac.ToolService/DownloadTool"
)

// ToolServiceClient is the client API for ToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolServiceClient interface {
	DownloadTool(ctx context.Context, in *DownloadToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolChunk], error)
}

type toolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolServiceClient(cc grpc.ClientConnInterface) ToolServiceClient {
	return &toolServiceClient{cc}
}

func (c *toolServiceClient) DownloadTool(ctx context.Context, in *DownloadToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ToolService_ServiceDesc.Streams[0], ToolService_DownloadTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadToolRequest, ToolChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_DownloadToolClient = grpc.ServerStreamingClient[ToolChunk]

// ToolServiceServer is the server API for ToolService service.
// All implementations must embed UnimplementedToolServiceServer
// for forward compatibility.
type ToolServiceServer interface {
	DownloadTool(*DownloadToolRequest, grpc.ServerStreamingServer[ToolChunk]) error
	mustEmbedUnimplementedToolServiceServer()
}

// UnimplementedToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolServiceServer struct{}

func (UnimplementedToolServiceServer) DownloadTool(*DownloadToolRequest, grpc.ServerStreamingServer[ToolChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadTool not implemented")
}
func (UnimplementedToolServiceServer) mustEmbedUnimplementedToolServiceServer() {}
func (UnimplementedToolServiceServer) testEmbeddedByValue()                     {}

// UnsafeToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolServiceServer will
// result in compilation errors.
type UnsafeToolServiceServer interface {
	mustEmbedUnimplementedToolServiceServer()
}

func RegisterToolServiceServer(s grpc.ServiceRegistrar, srv ToolServiceServer) {
	// If the following call panics, it indicates UnimplementedToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolService_ServiceDesc, srv)
}

func _ToolService_DownloadTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadToolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToolServiceServer).DownloadTool(m, &grpc.GenericServerStream[DownloadToolRequest, ToolChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ToolService_DownloadToolServer = grpc.ServerStreamingServer[ToolChunk]

// ToolService_ServiceDesc is the grpc.ServiceDesc for ToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tac.ToolService",
	HandlerType: (*ToolServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadTool",
			Handler:       _ToolService_DownloadTool_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tac.proto",
}

const (
	DaemonService_Ping_FullMethodName               = "/tac.DaemonService/Ping"
	DaemonService_StartTrigger_FullMethodName       = "/tac.DaemonService/StartTrigger"
	DaemonService_StopTrigger_FullMethodName        = "/tac.DaemonService/StopTrigger"
	DaemonService_RunTrigger_FullMethodName         = "/tac.DaemonService/RunTrigger"
	DaemonService_ListTriggers_FullMethodName       = "/tac.DaemonService/ListTriggers"
	DaemonService_ListEvents_FullMethodName         = "/tac.DaemonService/ListEvents"
	DaemonService_GetTriggerEvents_FullMethodName   = "/tac.DaemonService/GetTriggerEvents"
	DaemonService_CreateTrigger_FullMethodName      = "/tac.DaemonService/CreateTrigger"
	DaemonService_UpdateTrigger_FullMethodName      = "/tac.DaemonService/UpdateTrigger"
	DaemonService_DeleteTrigger_FullMethodName      = "/tac.DaemonService/DeleteTrigger"
	DaemonService_CreateEvent_FullMethodName        = "/tac.DaemonService/CreateEvent"
	DaemonService_UpdateEvent_FullMethodName        = "/tac.DaemonService/UpdateEvent"
	DaemonService_DeleteEvent_FullMethodName        = "/tac.DaemonService/DeleteEvent"
	DaemonService_ListEnvPresets_FullMethodName     = "/tac.DaemonService/ListEnvPresets"
	DaemonService_CreateEnvPreset_FullMethodName    = "/tac.DaemonService/CreateEnvPreset"
	DaemonService_UpdateEnvPreset_FullMethodName    = "/tac.DaemonService/UpdateEnvPreset"
	DaemonService_DeleteEnvPreset_FullMethodName    = "/tac.DaemonService/DeleteEnvPreset"
	DaemonService_GetDaemonStatus_FullMethodName    = "/tac.DaemonService/GetDaemonStatus"
	DaemonService_Shutdown_FullMethodName           = "/tac.DaemonService/Shutdown"
	DaemonService_ListActiveSessions_FullMethodName = "/tac.DaemonService/ListActiveSessions"
	DaemonService_WatchSession_FullMethodName       = "/tac.DaemonService/WatchSession"
)

// DaemonServiceClient is the client API for DaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DaemonServiceClient interface {
	Ping(ctx context.Context, in *DaemonPingRequest, opts ...grpc.CallOption) (*DaemonPingResponse, error)
	StartTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	StopTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	RunTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	ListTriggers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TriggerListResponse, error)
	ListEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EventListResponse, error)
	GetTriggerEvents(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*EventListResponse, error)
	CreateTrigger(ctx context.Context, in *CreateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	UpdateTrigger(ctx context.Context, in *UpdateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	DeleteTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error)
	CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	DeleteEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*EventResponse, error)
	ListEnvPresets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EnvPresetListResponse, error)
	CreateEnvPreset(ctx context.Context, in *CreateEnvPresetRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error)
	UpdateEnvPreset(ctx context.Context, in *UpdateEnvPresetRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error)
	DeleteEnvPreset(ctx context.Context, in *EnvPresetIDRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error)
	GetDaemonStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ListActiveSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActiveSessionListResponse, error)
	WatchSession(ctx context.Context, in *WatchSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error)
}

type daemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDaemonServiceClient(cc grpc.ClientConnInterface) DaemonServiceClient {
	return &daemonServiceClient{cc}
}

func (c *daemonServiceClient) Ping(ctx context.Context, in *DaemonPingRequest, opts ...grpc.CallOption) (*DaemonPingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonPingResponse)
	err := c.cc.Invoke(ctx, DaemonService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StartTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_StartTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) StopTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_StopTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) RunTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_RunTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListTriggers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TriggerListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListTriggers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetTriggerEvents(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*EventListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventListResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetTriggerEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateTrigger(ctx context.Context, in *CreateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_CreateTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateTrigger(ctx context.Context, in *UpdateTriggerRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_UpdateTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteTrigger(ctx context.Context, in *TriggerIDRequest, opts ...grpc.CallOption) (*TriggerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteTrigger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateEvent(ctx context.Context, in *CreateEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, DaemonService_CreateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, DaemonService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteEvent(ctx context.Context, in *EventIDRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListEnvPresets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*EnvPresetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvPresetListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListEnvPresets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) CreateEnvPreset(ctx context.Context, in *CreateEnvPresetRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvPresetResponse)
	err := c.cc.Invoke(ctx, DaemonService_CreateEnvPreset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) UpdateEnvPreset(ctx context.Context, in *UpdateEnvPresetRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvPresetResponse)
	err := c.cc.Invoke(ctx, DaemonService_UpdateEnvPreset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) DeleteEnvPreset(ctx context.Context, in *EnvPresetIDRequest, opts ...grpc.CallOption) (*EnvPresetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvPresetResponse)
	err := c.cc.Invoke(ctx, DaemonService_DeleteEnvPreset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) GetDaemonStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, DaemonService_GetDaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) Shutdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DaemonService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) ListActiveSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ActiveSessionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActiveSessionListResponse)
	err := c.cc.Invoke(ctx, DaemonService_ListActiveSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonServiceClient) WatchSession(ctx context.Context, in *WatchSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DaemonService_ServiceDesc.Streams[0], DaemonService_WatchSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchSessionRequest, ChatMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_WatchSessionClient = grpc.ServerStreamingClient[ChatMessage]

// DaemonServiceServer is the server API for DaemonService service.
// All implementations must embed UnimplementedDaemonServiceServer
// for forward compatibility.
type DaemonServiceServer interface {
	Ping(context.Context, *DaemonPingRequest) (*DaemonPingResponse, error)
	StartTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error)
	StopTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error)
	RunTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error)
	ListTriggers(context.Context, *Empty) (*TriggerListResponse, error)
	ListEvents(context.Context, *Empty) (*EventListResponse, error)
	GetTriggerEvents(context.Context, *TriggerIDRequest) (*EventListResponse, error)
	CreateTrigger(context.Context, *CreateTriggerRequest) (*TriggerResponse, error)
	UpdateTrigger(context.Context, *UpdateTriggerRequest) (*TriggerResponse, error)
	DeleteTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error)
	CreateEvent(context.Context, *CreateEventRequest) (*EventResponse, error)
	UpdateEvent(context.Context, *UpdateEventRequest) (*EventResponse, error)
	DeleteEvent(context.Context, *EventIDRequest) (*EventResponse, error)
	ListEnvPresets(context.Context, *Empty) (*EnvPresetListResponse, error)
	CreateEnvPreset(context.Context, *CreateEnvPresetRequest) (*EnvPresetResponse, error)
	UpdateEnvPreset(context.Context, *UpdateEnvPresetRequest) (*EnvPresetResponse, error)
	DeleteEnvPreset(context.Context, *EnvPresetIDRequest) (*EnvPresetResponse, error)
	GetDaemonStatus(context.Context, *Empty) (*DaemonStatusResponse, error)
	Shutdown(context.Context, *Empty) (*Empty, error)
	ListActiveSessions(context.Context, *Empty) (*ActiveSessionListResponse, error)
	WatchSession(*WatchSessionRequest, grpc.ServerStreamingServer[ChatMessage]) error
	mustEmbedUnimplementedDaemonServiceServer()
}

// UnimplementedDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDaemonServiceServer struct{}

func (UnimplementedDaemonServiceServer) Ping(context.Context, *DaemonPingRequest) (*DaemonPingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDaemonServiceServer) StartTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) StopTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) RunTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) ListTriggers(context.Context, *Empty) (*TriggerListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTriggers not implemented")
}
func (UnimplementedDaemonServiceServer) ListEvents(context.Context, *Empty) (*EventListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedDaemonServiceServer) GetTriggerEvents(context.Context, *TriggerIDRequest) (*EventListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTriggerEvents not implemented")
}
func (UnimplementedDaemonServiceServer) CreateTrigger(context.Context, *CreateTriggerRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateTrigger(context.Context, *UpdateTriggerRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteTrigger(context.Context, *TriggerIDRequest) (*TriggerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTrigger not implemented")
}
func (UnimplementedDaemonServiceServer) CreateEvent(context.Context, *CreateEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEvent not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteEvent(context.Context, *EventIDRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedDaemonServiceServer) ListEnvPresets(context.Context, *Empty) (*EnvPresetListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnvPresets not implemented")
}
func (UnimplementedDaemonServiceServer) CreateEnvPreset(context.Context, *CreateEnvPresetRequest) (*EnvPresetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnvPreset not implemented")
}
func (UnimplementedDaemonServiceServer) UpdateEnvPreset(context.Context, *UpdateEnvPresetRequest) (*EnvPresetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnvPreset not implemented")
}
func (UnimplementedDaemonServiceServer) DeleteEnvPreset(context.Context, *EnvPresetIDRequest) (*EnvPresetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEnvPreset not implemented")
}
func (UnimplementedDaemonServiceServer) GetDaemonStatus(context.Context, *Empty) (*DaemonStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDaemonStatus not implemented")
}
func (UnimplementedDaemonServiceServer) Shutdown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedDaemonServiceServer) ListActiveSessions(context.Context, *Empty) (*ActiveSessionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveSessions not implemented")
}
func (UnimplementedDaemonServiceServer) WatchSession(*WatchSessionRequest, grpc.ServerStreamingServer[ChatMessage]) error {
	return status.Error(codes.Unimplemented, "method WatchSession not implemented")
}
func (UnimplementedDaemonServiceServer) mustEmbedUnimplementedDaemonServiceServer() {}
func (UnimplementedDaemonServiceServer) testEmbeddedByValue()                       {}

// UnsafeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DaemonServiceServer will
// result in compilation errors.
type UnsafeDaemonServiceServer interface {
	mustEmbedUnimplementedDaemonServiceServer()
}

func RegisterDaemonServiceServer(s grpc.ServiceRegistrar, srv DaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DaemonService_ServiceDesc, srv)
}

func _DaemonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DaemonPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Ping(ctx, req.(*DaemonPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StartTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StartTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StartTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StartTrigger(ctx, req.(*TriggerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_StopTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).StopTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_StopTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).StopTrigger(ctx, req.(*TriggerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_RunTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).RunTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_RunTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).RunTrigger(ctx, req.(*TriggerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListTriggers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListTriggers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListTriggers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListTriggers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListEvents(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetTriggerEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetTriggerEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetTriggerEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetTriggerEvents(ctx, req.(*TriggerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateTrigger(ctx, req.(*CreateTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UpdateTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateTrigger(ctx, req.(*UpdateTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteTrigger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteTrigger(ctx, req.(*TriggerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateEvent(ctx, req.(*CreateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteEvent(ctx, req.(*EventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListEnvPresets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListEnvPresets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListEnvPresets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListEnvPresets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_CreateEnvPreset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnvPresetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).CreateEnvPreset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_CreateEnvPreset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).CreateEnvPreset(ctx, req.(*CreateEnvPresetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_UpdateEnvPreset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvPresetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).UpdateEnvPreset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_UpdateEnvPreset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).UpdateEnvPreset(ctx, req.(*UpdateEnvPresetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_DeleteEnvPreset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvPresetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).DeleteEnvPreset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_DeleteEnvPreset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).DeleteEnvPreset(ctx, req.(*EnvPresetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_GetDaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).GetDaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_GetDaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).GetDaemonStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).Shutdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_ListActiveSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServiceServer).ListActiveSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DaemonService_ListActiveSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServiceServer).ListActiveSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaemonService_WatchSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DaemonServiceServer).WatchSession(m, &grpc.GenericServerStream[WatchSessionRequest, ChatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DaemonService_WatchSessionServer = grpc.ServerStreamingServer[ChatMessage]

// DaemonService_ServiceDesc is the grpc.ServiceDesc for DaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tac.DaemonService",
	HandlerType: (*DaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DaemonService_Ping_Handler,
		},
		{
			MethodName: "StartTrigger",
			Handler:    _DaemonService_StartTrigger_Handler,
		},
		{
			MethodName: "StopTrigger",
			Handler:    _DaemonService_StopTrigger_Handler,
		},
		{
			MethodName: "RunTrigger",
			Handler:    _DaemonService_RunTrigger_Handler,
		},
		{
			MethodName: "ListTriggers",
			Handler:    _DaemonService_ListTriggers_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _DaemonService_ListEvents_Handler,
		},
		{
			MethodName: "GetTriggerEvents",
			Handler:    _DaemonService_GetTriggerEvents_Handler,
		},
		{
			MethodName: "CreateTrigger",
			Handler:    _DaemonService_CreateTrigger_Handler,
		},
		{
			MethodName: "UpdateTrigger",
			Handler:    _DaemonService_UpdateTrigger_Handler,
		},
		{
			MethodName: "DeleteTrigger",
			Handler:    _DaemonService_DeleteTrigger_Handler,
		},
		{
			MethodName: "CreateEvent",
			Handler:    _DaemonService_CreateEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _DaemonService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _DaemonService_DeleteEvent_Handler,
		},
		{
			MethodName: "ListEnvPresets",
			Handler:    _DaemonService_ListEnvPresets_Handler,
		},
		{
			MethodName: "CreateEnvPreset",
			Handler:    _DaemonService_CreateEnvPreset_Handler,
		},
		{
			MethodName: "UpdateEnvPreset",
			Handler:    _DaemonService_UpdateEnvPreset_Handler,
		},
		{
			MethodName: "DeleteEnvPreset",
			Handler:    _DaemonService_DeleteEnvPreset_Handler,
		},
		{
			MethodName: "GetDaemonStatus",
			Handler:    _DaemonService_GetDaemonStatus_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _DaemonService_Shutdown_Handler,
		},
		{
			MethodName: "ListActiveSessions",
			Handler:    _DaemonService_ListActiveSessions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchSession",
			Handler:       _DaemonService_WatchSession_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tac.proto",
}
